Fix for Error 500 when clicking submit after editing information about a case.
The cause is an error of   AttributeError: 'int' object has no attribute 'isdigit'